Allow ModuleClassLoader to optionally delegate class-loading to parent
MinecraftForge/securejarhandler pull request #60
Opened 2023-12-23 10:36 UTC by shartte

The goal is to add a new entrypoint to https://github.com/McModLauncher/bootstraplauncher for JUnit runners, which disables classloader isolation. This change adds the needed constructor to ModuleClassLoader to enable that.

This is used to allow test-classes to live in the GAME layer, while still loading JUnit and  other testing library classes found on the normal classpath. When being run by a unit testing framework, we do **not** control the JVM entrypoint like we normally do, and Gradle for example will class-load JUnit before calling any other hook. Our test classes need to refer to those same loaded classes, making it easier if isolation is disabled in such scenarios.

2023-12-23 10:53 UTC, Matyrobbrt approved these changes

2023-12-23 11:03 UTC, Su5eD approved these changes

2023-12-26 19:57 UTC, marchermans commented
So, principally, I understand this idea.
However, given that we usually do this with a filter instead of a blanket allow-all, I was wondering if you had any way of figuring out if such a filter was even possible in this case?

2024-01-09 07:28 UTC, marchermans requested changes
I have thought about this for a while.

Allthough I am convinced that the JUnit API provides other, more standardized, ways of doing testing in a modularly isolated environment, right now we do not have the time.

As such this is at least a bridge and a gap to allow for this to work.

However, since I want to be clear that this should not be used in production, what so ever, I want a very load warning in the source code, in the form of previously mentioned annotations and documentation. As well as, a very loud warning in a log file!

Please add those and then this is good.

2024-01-09 07:28 UTC, marchermans commented on src/main/java/cpw/mods/cl/ModuleClassLoader.java
> +    public ModuleClassLoader(final String name, final Configuration configuration, final List<ModuleLayer> parentLayers, @Nullable ClassLoader parentLoader) {
Add an annotation @VisibleForTesting, add a lot of documentation and warnings that this is not supposed to be used in production.

Add a logger and a warning output that the game is starting in none-isolated mode, that this is for unit testing only, and that this will cause issues in production.

2024-01-12 14:45 UTC, Matyrobbrt commented on src/main/java/cpw/mods/cl/ModuleClassLoader.java
> +    public ModuleClassLoader(final String name, final Configuration configuration, final List<ModuleLayer> parentLayers, @Nullable ClassLoader parentLoader) {
I think logging here will just increase the logspam, which should be reduced, not increased in the case of tests (otherwise errors become harder to track). This won't leak to neo production, logging isn't necessary.

2024-01-12 14:48 UTC, marchermans commented on src/main/java/cpw/mods/cl/ModuleClassLoader.java
> +    public ModuleClassLoader(final String name, final Configuration configuration, final List<ModuleLayer> parentLayers, @Nullable ClassLoader parentLoader) {
Given that this is not Neo, but MCModLauncher, what neo does or does not do is not relevant in this repository.

The general principal we follow in this project is that we log code paths takes that are not **normal**. Whether you like it or not, this is not a normal code path, and as such a line like: `Starting modlauncher in unit test mode` is not log spam. In case of errors this is a vitually important line to determine what entry point as such what class loader isolation state is used.

2024-01-12 15:13 UTC, Technici4n commented on src/main/java/cpw/mods/cl/ModuleClassLoader.java
> +    public ModuleClassLoader(final String name, final Configuration configuration, final List<ModuleLayer> parentLayers, @Nullable ClassLoader parentLoader) {
The info log should probably be in BSL not in SJH.

2024-01-12 17:45 UTC, marchermans commented on src/main/java/cpw/mods/cl/ModuleClassLoader.java
> +    public ModuleClassLoader(final String name, final Configuration configuration, final List<ModuleLayer> parentLayers, @Nullable ClassLoader parentLoader) {
Maybe, argueably it should be somewhere.

2024-01-12 19:40 UTC, Technici4n commented on src/main/java/cpw/mods/cl/ModuleClassLoader.java
> +     * <p/>
Cursed, should really be `<p>`

2024-01-13 18:11 UTC, marchermans approved these changes

2024-01-13 18:11 UTC, merged