Add close() methods throughout the SecureJar->JarContents chain to allow closing the backing file systems
MinecraftForge/securejarhandler pull request #68
Opened 2024-04-12 14:17 UTC by shartte

**BREAKING CHANGE**

2024-04-20 12:04 UTC, Technici4n commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +        for (var embeddedFs : embeddedFileSystems.values()) {
Technically if there is an exception here, the remaining file systems won't get closed.

2024-04-25 18:59 UTC, marchermans requested changes

2024-04-25 18:59 UTC, marchermans commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +        for (var embeddedFs : embeddedFileSystems.values()) {
Please surround the underlying close calls with a try-catch and continue closing the remaining File systems.

2024-06-02 15:55 UTC, shartte commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +        for (var embeddedFs : embeddedFileSystems.values()) {
Addressed

2024-06-02 15:56 UTC, shartte commented on src/main/java/cpw/mods/niofs/union/UnionFileSystem.java
> +        for (var embeddedFs : embeddedFileSystems.values()) {
Addressed

2024-06-02 16:42 UTC, Matyrobbrt requested changes

2024-06-02 16:42 UTC, Matyrobbrt commented on src/main/java/cpw/mods/jarhandling/SecureJar.java
> +    void close() throws IOException;
You can extend Closeable instead.

2024-06-02 17:32 UTC, shartte commented on src/main/java/cpw/mods/jarhandling/SecureJar.java
> +    void close() throws IOException;
... that just reintroduces the implementation of AutoClosable

public interface Closeable
extends [AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html)

And that seriously disables the warning?

2024-06-02 18:18 UTC, shartte commented on src/main/java/cpw/mods/jarhandling/SecureJar.java
> +    void close() throws IOException;
Will leave it like this

2024-06-02 18:37 UTC, Matyrobbrt approved these changes

2024-06-02 19:00 UTC, marchermans approved these changes

2024-06-02 21:44 UTC, merged